### ISSUE TITLE
Is there a paper for this published yet?

### ISSUE THREAD

**Issue by micahscopes** [crdt-ibm-research/json-delta-crdt#12]
This repo looks real interesting... I'm curious to know if there's a completed paper that accompanies it?

**Comment by guykhazma** [comment]
Hi @micahscopes,

A paper titled "DSON: JSON CRDT Using Delta-Mutations For Document Stores" accompanying the implementation will be published in VLDB 2022.

cc: @ArikRinberg

**Comment by ArikRinberg** [comment]
@micahscopes The paper is now published, alongside an accompanying video.
[3510397.3510403.pdf](https://github.com/crdt-ibm-research/json-delta-crdt/files/9498127/3510397.3510403.pdf)
